### ISSUE TITLE
Deploy Doccona application to Azure

### ISSUE THREAD

**Issue by joelbudu** [GhanaNLP/ghananlp.github.io#8]
We need to host a version of this application on our Azure servers.

https://github.com/doccano/doccano

**Comment by DanielKomlaElijah** [comment]
Deployment successful

https://doccano-new.azurewebsites.net

**Comment by joelbudu** [comment]
Thanks a lot @DanielKomlaElijah .

**Comment by DanielKomlaElijah** [comment]
> Thanks a lot @DanielKomlaElijah .

Happy to help @joelbudu
